# Generated by Django 5.2.8 on 2025-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderun_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='color',
            field=models.CharField(default='red'),
        ),
    ]
